# Generated by Django 5.0.1 on 2024-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
