# Generated by Django 5.0.1 on 2024-05-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_lesson_yt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
