# Generated by Django 5.0.1 on 2024-05-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.lesson'),
        ),
    ]
