# Generated by Django 5.0.1 on 2024-04-06 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='course.section'),
            preserve_default=False,
        ),
    ]
