# Generated by Django 5.0.1 on 2024-02-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='progress.progress'),
            preserve_default=False,
        ),
    ]
