# Generated by Django 5.0.1 on 2024-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('done', 'Done')], default='started', max_length=20),
        ),
    ]
