# Generated by Django 5.0.1 on 2024-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_enrollment_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Progress'),
        ),
    ]
