# Generated by Django 5.0.1 on 2024-02-09 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(choices=[('I+', 'I Positive'), ('I-', 'I Negative'), ('II+', 'II Positive'), ('II-', 'II Negative'), ('III+', 'III Positive'), ('III-', 'III Negative'), ('IV+', 'IV Positive'), ('IV-', 'IV Negative'), ('not_specified', 'Not specified')], default='not_specified', max_length=15, verbose_name='blood_group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_specified', 'Not Specified')], default='not_specified', max_length=15, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+7XXXXXXXXXX'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
