# Generated by Django 5.0.1 on 2024-05-29 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='date',
            field=models.DateField(default='2003-03-21', verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
