# Generated by Django 5.0.1 on 2024-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_blood_group_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
