# Generated by Django 5.0.1 on 2024-04-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default-avatar.jpg', upload_to='profile_images', verbose_name='avatar'),
        ),
    ]
